server {
    listen 80;
    listen [::]:80;
    server_name itamishotaro.com www.itamishotaro.com;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name itamishotaro.com www.itamishotaro.com;

    root /var/www/html;
    index index.html;

    ssl_certificate     /etc/ssl/cloudflare/origin-cert.pem;
    ssl_certificate_key /etc/ssl/cloudflare/origin-key.pem;

    location / {
        try_files $uri $uri/ =404;
    }
}
